image: node:20

pipelines:
  branches:
    dev:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            expire_in: 1 hrs
            paths:
              - out/**

      - step:
          name: Upload to Dev S3
          script:
            - apt-get update && apt-get install -y python3-pip python3-venv
            - python3 -m venv myenv
            - source myenv/bin/activate
            - pip install awscli
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - aws s3 sync ./out s3://$DEV_AWS_BUCKET/
            - deactivate
      - step:
          name: CloudFront Invalidation
          script:
            - apt-get update && apt-get install -y python3-pip
            - pip3 install awscli
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - aws configure set region $AWS_REGION
            - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run build
          artifacts:
            expire_in: 1 hrs
            paths:
              - out/**

      - step:
          name: Upload to Production S3
          script:
            - apt-get update && apt-get install -y python3-pip python3-venv
            - python3 -m venv myenv
            - source myenv/bin/activate
            - pip install awscli
            - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            - aws s3 sync ./out s3://$PROD_AWS_BUCKET/
            - deactivate
