export const pathHelper = {
    '/': null,
    '/home/': null,
    '/register/': false,
    '/login/': false,
    '/dashboard/': true,
    '/dashboard/profile/': true,
    '/dashboard/invoices/': true,
    '/dashboard/installations/': true,
    '/recover-password/': true,
    '/fail/out-of-range/': false,
    '/fail/low-cost/': false,
    '/connection/': true,
}

export const helperToPath = {
    '/': "na+home+da",
    '/home/': "na+home+da",
    '/signup/': "na+tela+de+cadastro+da",
    '/register/': "no+cadastro+da",
    '/login/': "no+login+da",
    '/dashboard/': "no+painel+da",
    '/profile/': "no+meu+perfil+da",
    '/invoices/': "na+pagina+de+faturas+da",
    '/installations/': "na+pagina+de+enderecos+da",
    '/fail/out-of-range/': "na+pagina+de+fora+da+regiao+de+cobertura+da",
    '/fail/low-cost/': "na+pagina+de+baixo+custo+da",
    '/connection/': "na+pagina+de+conexao+do+perfil+da",
}

export const headerHelper = {
    '/': "newhomedesktop",
    '/home/': "newhomedesktop",
    '/signup/': "newhomedesktop",
    '/register/': false,
    '/dashboard/': true,
    '/dashboard/profile/': true,
    '/dashboard/invoices/': true,
    '/dashboard/installations/': true,
    '/recover-password/': true,
    '/fail/out-of-range/': false,
    '/fail/low-cost/': false,
    '/connection/': true,
}
export const newHeaderHelper = {
    '/': true,
    '/home/': true,
    '/signup/': true,
    '/register/': false,
    '/dashboard/': false,
    '/dashboard/profile/': false,
    '/dashboard/invoices/': false,
    '/dashboard/installations/': false,
    '/recover-password/': false,
    '/fail/out-of-range/': false,
    '/fail/low-cost/': false,
    '/connection/': false,
}