export const pathHelper = {
    '/': null,
    '/home/': null,
    '/register/': false,
    '/login/': false,
    '/lp/': false,
    '/lp/novos-clientes/': false,
    '/dashboard/': true,
    '/dashboard/profile/': true,
    '/dashboard/invoices/': true,
    '/dashboard/installations/': true,
    '/recover-password/': true,
    '/fail/out-of-range/': false,
    '/fail/low-cost/': false,
    '/connection/': true,
}

export const headerHelper = {
    '/': false,
    '/home/': false,
    '/signup/': false,
    '/lp/': false,
    '/lp/novos-clientes/': false,
    '/lp/presentation/': false,
    '/register/': false,
    '/dashboard/': true,
    '/dashboard/profile/': true,
    '/dashboard/invoices/': true,
    '/dashboard/installations/': true,
    '/recover-password/': true,
    '/fail/out-of-range/': false,
    '/fail/low-cost/': false,
    '/connection/': true,
}
export const landingPageHelper = {
    '/': false,
    '/lp/': true,
    '/lp/novos-clientes/': true,
    '/lp/presentation/': true,
}

export const helperToPath = {
    '/': "na+home",
    '/home/': "na+home",
    '/signup/': "no+cadastro",
    '/login/': "no+login",
    '/lp/novos-clientes/': "na+landing+page+de+novos+clientes",
    '/lp/apresentacao/': "na+landing+page+de+apresentação",
    '/dashboard/': "no+dashboard",
    '/dashboard/profile/': "na+minha+pagina+de+perfil",
    '/dashboard/invoices/': "na+pagina+de+faturas",
    '/dashboard/installations/': "na+pagina+meus+enderecos",
    '/recover-password/': "na+pagina+de+recuperar+senha",
    '/fail/out-of-range/': "na+pagina+de+fora+de+região",
    '/fail/low-cost/': "na+pagina+de+baixo+custo",
    '/connection/': "na+pagina+de+conexão",
}