export const statesIdOptions = {
    "ACRE": 1,
    "ALAGOAS": 2,
    "AMAPÁ": 3,
    "AMAZONAS": 4,
    "BAHIA": 5,
    "CEARÁ": 6,
    "DISTRITO FEDERAL": 7,
    "ESPÍRITO SANTO": 8,
    "RORAIMA": 9,
    "GOIÁS": 10,
    "MARANHÃO": 11,
    "MATO GROSSO": 12,
    "MATO GROSSO DO SUL": 13,
    "MINAS GERAIS": 14,
    "PARÁ": 15,
    "PARAÍBA": 16,
    "PARANÁ": 17,
    "PERNAMBUCO": 18,
    "PIAUÍ": 19,
    "RIO DE JANEIRO": 20,
    "RIO GRANDE DO NORTE": 21,
    "RIO GRANDE DO SUL": 22,
    "RONDÔNIA": 23,
    "TOCANTINS": 24,
    "SANTA CATARINA": 25,
    "SÃO PAULO": 26,
    "SERGIPE": 27
};


export const statesAcronymOptions = {
    "AC": 1,
    "AL": 2,
    "AP": 3,
    "AM": 4,
    "BA": 5,
    "CE": 6,
    "DF": 7,
    "ES": 8,
    "RR": 9,
    "GO": 10,
    "MA": 11,
    "MT": 12,
    "MS": 13,
    "MG": 14,
    "PA": 15,
    "PB": 16,
    "PR": 17,
    "PE": 18,
    "PI": 19,
    "RJ": 20,
    "RN": 21,
    "RS": 22,
    "RO": 23,
    "TO": 24,
    "SC": 25,
    "SP": 26,
    "SE": 27
};

